### PR TITLE
Create c-cpp.yml

### PR DESCRIPTION
**Pull request by yassinouk**
Build and run csvfind:
1- Compiled the csvfind.c file using gcc and created the csvfind executable.
2- Executed csvfind with the provided input arguments in the example from the README file.
Let me know if you have any questions or need further clarification.

### CODE REVIEW

**Comment by unconv** [comment]
Thanks! I'm new to CI and have been meaning to learn it, so this is great. Do I need to do something other than add this file to the repo? Does it need to be enabled separately?

**Comment by unconv** [comment]
I merged your pull request and seems that the CI is running now. Cool!

**Comment by yassinouk** [comment]
### Ideally, I prefer to put the CI workflow in a separate branch for the following reasons:

#### 1- _Isolation:_ This can be useful when you want to have a dedicated branch for testing and development purposes.

#### 2- _Stability:_ This way, any changes to the workflow can be thoroughly tested and reviewed before being merged into the main branch.

#### Ultimately, the choice between using a separate branch or the main branch for the CI workflow depends on the project's complexity, requirements, and other factors.
PS: I will enhance the workflow with cool things in the future, like greeting contributors and testing different versions of code (PHP, Rust). ✌

**Comment by unconv** [comment]
Good stuff. How would testing the correctness of the output be done? Since I guess right now the CI just checks if the csvfind binary runs without errors. But even if it prints out nothing, or a wrong output, it will pass the CI. Immediately I think of writing a bash script that would compile the code, run it with different inputs and check the output. This bash script would then be run in the CI. But that's perhaps a bit of a hacky way of doing it...

**Pull request merged**
